# Generated by Django 4.2.3 on 2023-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='الاسم:')),
                ('surname', models.CharField(max_length=50, verbose_name='اللقب:')),
                ('subtitle', models.CharField(max_length=50, verbose_name='نبذه عنك:')),
                ('address', models.CharField(max_length=50, verbose_name='المحافظه:')),
                ('address_details', models.CharField(max_length=50, verbose_name='العنوان بالتفصيل:')),
                ('number_phone', models.CharField(max_length=50, verbose_name='الهاتف:')),
                ('working_hours', models.CharField(max_length=50, verbose_name='ساعات العمل:')),
                ('waiting_time', models.IntegerField(blank=True, null=True, verbose_name='مده الانتظار:')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True, verbose_name='من انا:')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='سعر الكشق:')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('google', models.CharField(blank=True, max_length=100, null=True)),
                ('join_new', models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام:')),
                ('type_of_person', models.CharField(choices=[('انثي', 'انثي'), ('رجل', 'رجل')], max_length=50, verbose_name='النوع:')),
                ('doctor', models.CharField(blank=True, choices=[('جراحه اطفال', 'جراحه اطفال'), ('نفسي', 'نفسي'), ('اورام', 'اورام'), ('اسنان', 'اسنان'), ('جلديه', 'جلديه'), ('جراحه سمنه و مناظير', 'جراحه سمنه و مناظير'), ('باطنه', 'باطنه'), ('جراحه اوعيه دمويه', 'جراحه اوعيه دمويه'), ('امراض دم', 'امراض دم'), ('مخ و اعصاب', 'مخ و اعصاب'), ('قلب و اعيه دمويه', 'فلب و اعيه دمويه'), ('جراحه تجميل', 'جراحه تجميل'), ('جراحه اورام', 'جراحه اورام'), ('نساء و توليد', 'نساء و توليد'), ('عظام', 'عظام'), ('انف و اذن', 'انف و اذن'), ('اطفال حديثي الولاده', 'اطفال حديثي الولاده'), ('تخسيس و تغذيه', 'تخسيس و تغذيه')], max_length=50, null=True, verbose_name='الدكتور ؟')),
                ('specialist_doctor', models.CharField(blank=True, max_length=100, null=True, verbose_name='متخصص في؟')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='الصوره الشخصيه:')),
            ],
        ),
    ]
